/**
 * Kalorimetre MASTER Food Database — MVP Nutrition Dataset
 *
 * Source of truth: natural serving macros (NOT per 100 g).
 * calories / protein / carbs / fat = values for serving_size (e.g. "1 Kase").
 * calories always equals Atwater sum: 4×Protein + 4×Carbs + 9×Fat.
 *
 * FOOD_DB is a legacy projection for UI calcPreview / unit scaling.
 */

/** Atwater general factors */
export function macroCalories(protein, carbs, fat) {
  return Math.round(protein * 4 + carbs * 4 + fat * 9)
}

/** Review metadata for newly added catalog entries (pending USDA verification). */
export const PENDING_REVIEW = {
  source_type: 'LOCAL_MASTER_PENDING_VERIFICATION',
  source_name: 'foodDatabase.js',
  source_food_id: null,
  review_status: 'pending_verification',
}

/** Default review metadata for legacy master catalog entries. */
export const LEGACY_REVIEW = {
  source_type: 'LOCAL_MASTER',
  source_name: 'foodDatabase.js',
  source_food_id: null,
  review_status: 'legacy_master',
}

/** Parse "1 Kase" → { qty: 1, unit: "Kase" } */
export function parseServingSize(servingSize) {
  const m = String(servingSize || '').match(/^(\d+(?:\.\d+)?)\s+(.+)$/)
  if (m) return { qty: parseFloat(m[1]), unit: m[2] }
  return { qty: 1, unit: servingSize || 'Porsiyon' }
}

/** Build legacy FOOD_DB row from a master entry (UI basket scaling). */
export function toLegacyFood(master) {
  const { unit } = parseServingSize(master.serving_size)
  const mult = Math.max(master.serving_grams / 100, 0.01)

  const legacy = {
    id: master.id,
    slug: master.slug,
    name: master.name,
    calories: master.calories / mult,
    protein: master.protein / mult,
    carbs: master.carbs / mult,
    fat: master.fat / mult,
    units: { Gram: 0.01, [unit]: mult },
    tags: master.tags ?? [],
    serving_size: master.serving_size,
    data_source: master.data_source,
    review: master.review ?? LEGACY_REVIEW,
    _natural: {
      calories: master.calories,
      protein: master.protein,
      carbs: master.carbs,
      fat: master.fat,
      unit,
      grams: master.serving_grams,
    },
  }

  if (unit === 'Bardak' || unit === 'Fincan' || unit === 'Su Bardağı') {
    legacy.units.Mililitre = 0.01
  }

  return legacy
}

export const MASTER_FOOD_DB = [
  {
    id: 1,
    slug: 'izgara_kofte',
    name: 'Izgara Köfte',
    calories: 309,
    protein: 27,
    carbs: 3,
    fat: 21,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 2,
    slug: 'tavuk_gogsu_izgara',
    name: 'Tavuk Göğsü (Izgara)',
    calories: 229,
    protein: 46,
    carbs: 0,
    fat: 5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 3,
    slug: 'yulaf_ezmesi',
    name: 'Yulaf Ezmesi',
    calories: 191,
    protein: 8,
    carbs: 33,
    fat: 3,
    serving_size: '1 Kase',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 4,
    slug: 'mercimek_corbasi',
    name: 'Mercimek Çorbası',
    calories: 155,
    protein: 10,
    carbs: 22,
    fat: 3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI', 'Akdeniz'],
  },

  {
    id: 5,
    slug: 'tam_bugday_ekmek',
    name: 'Tam Buğday Ekmek',
    calories: 85,
    protein: 5,
    carbs: 14,
    fat: 1,
    serving_size: '1 Dilim',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 6,
    slug: 'haslanmis_yumurta',
    name: 'Haşlanmış Yumurta',
    calories: 71,
    protein: 6,
    carbs: 0.6,
    fat: 5,
    serving_size: '1 Adet',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 7,
    slug: 'pirinc_pilavi',
    name: 'Pirinç Pilavı',
    calories: 189,
    protein: 4,
    carbs: 42,
    fat: 0.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 8,
    slug: 'kuru_fasulye',
    name: 'Kuru Fasulye',
    calories: 283,
    protein: 18,
    carbs: 46,
    fat: 3,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 9,
    slug: 'zeytinyagli_salata',
    name: 'Zeytinyağlı Salata',
    calories: 128,
    protein: 2.3,
    carbs: 6,
    fat: 10.5,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Akdeniz', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 10,
    slug: 'tam_yagli_sut',
    name: 'Tam Yağlı Süt',
    calories: 123,
    protein: 6.4,
    carbs: 9.6,
    fat: 6.6,
    serving_size: '1 Su Bardağı',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 11,
    slug: 'somon_izgara',
    name: 'Somon (Izgara)',
    calories: 300,
    protein: 30,
    carbs: 0,
    fat: 20,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Akdeniz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 12,
    slug: 'kinoa',
    name: 'Kinoa',
    calories: 178,
    protein: 6.6,
    carbs: 31.5,
    fat: 2.8,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Düşük GI'],
  },

  {
    id: 13,
    slug: 'avokado',
    name: 'Avokado',
    calories: 269,
    protein: 3,
    carbs: 13.5,
    fat: 22.5,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Keto', 'Akdeniz', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 14,
    slug: 'yogurt_tam_yagli',
    name: 'Yoğurt (Tam Yağlı)',
    calories: 94,
    protein: 5.3,
    carbs: 7.1,
    fat: 4.9,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 15,
    slug: 'nohut_haslanmis',
    name: 'Nohut (Haşlanmış)',
    calories: 251,
    protein: 13.4,
    carbs: 40.5,
    fat: 3.9,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI', 'Akdeniz'],
  },

  {
    id: 16,
    slug: 'badem',
    name: 'Badem',
    calories: 8,
    protein: 0.3,
    carbs: 0.3,
    fat: 0.6,
    serving_size: '1 Adet',
    serving_grams: 1.2,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Keto', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 17,
    slug: 'ispanak_cig',
    name: 'Ispanak (Çiğ)',
    calories: 12,
    protein: 1.2,
    carbs: 1.4,
    fat: 0.2,
    serving_size: '1 Kase',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Akdeniz', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 18,
    slug: 'tatli_patates',
    name: 'Tatlı Patates',
    calories: 105,
    protein: 1.9,
    carbs: 24,
    fat: 0.1,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 19,
    slug: 'lor_peyniri',
    name: 'Lor Peyniri',
    calories: 14,
    protein: 1.7,
    carbs: 0.5,
    fat: 0.6,
    serving_size: '1 Yemek Kaşığı',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 20,
    slug: 'zeytinyagi',
    name: 'Zeytinyağı',
    calories: 135,
    protein: 0,
    carbs: 0,
    fat: 15,
    serving_size: '1 Yemek Kaşığı',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Keto', 'Akdeniz', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 21,
    slug: 'simit',
    name: 'Simit',
    calories: 283,
    protein: 9,
    carbs: 55,
    fat: 3,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 22,
    slug: 'beyaz_peynir',
    name: 'Beyaz Peynir',
    calories: 80,
    protein: 4.3,
    carbs: 1.2,
    fat: 6.4,
    serving_size: '1 Dilim',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 23,
    slug: 'menemen',
    name: 'Menemen',
    calories: 297,
    protein: 14,
    carbs: 13,
    fat: 21,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 24,
    slug: 'omlet',
    name: 'Omlet',
    calories: 120,
    protein: 8.5,
    carbs: 0.5,
    fat: 9.3,
    serving_size: '1 Adet',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 25,
    slug: 'pogaca_peynirli',
    name: 'Poğaça (Peynirli)',
    calories: 290,
    protein: 7.6,
    carbs: 36,
    fat: 12.8,
    serving_size: '1 Adet',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 26,
    slug: 'doner_tavuk',
    name: 'Döner (Tavuk)',
    calories: 225,
    protein: 33,
    carbs: 4.5,
    fat: 8.3,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 27,
    slug: 'doner_et',
    name: 'Döner (Et)',
    calories: 342,
    protein: 29.4,
    carbs: 4.2,
    fat: 23.1,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 28,
    slug: 'lahmacun',
    name: 'Lahmacun',
    calories: 256,
    protein: 13,
    carbs: 33,
    fat: 8,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 29,
    slug: 'pide_kasarli',
    name: 'Pide (Kaşarlı)',
    calories: 700,
    protein: 31.3,
    carbs: 87.5,
    fat: 25,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 30,
    slug: 'borek_peynirli_firin',
    name: 'Börek (Peynirli, Fırın)',
    calories: 265,
    protein: 9.4,
    carbs: 25.9,
    fat: 13.8,
    serving_size: '1 Dilim',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 31,
    slug: 'manti',
    name: 'Mantı',
    calories: 555,
    protein: 28.5,
    carbs: 73.8,
    fat: 16.2,
    serving_size: '1 Porsiyon',
    serving_grams: 300,
    data_source: 'MASTER_DB',
    tags: ['Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 32,
    slug: 'i_skender_kebap',
    name: 'İskender Kebap',
    calories: 723,
    protein: 49,
    carbs: 53,
    fat: 35,
    serving_size: '1 Porsiyon',
    serving_grams: 350,
    data_source: 'MASTER_DB',
    tags: ['Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 33,
    slug: 'bulgur_pilavi',
    name: 'Bulgur Pilavı',
    calories: 308,
    protein: 11.2,
    carbs: 60,
    fat: 2.6,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 34,
    slug: 'makarna_haslanmis',
    name: 'Makarna (Haşlanmış)',
    calories: 261,
    protein: 10,
    carbs: 50.4,
    fat: 2.2,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 35,
    slug: 'domates_corbasi',
    name: 'Domates Çorbası',
    calories: 123,
    protein: 4,
    carbs: 20,
    fat: 3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 36,
    slug: 'tavuk_corbasi',
    name: 'Tavuk Çorbası',
    calories: 38,
    protein: 4.5,
    carbs: 2,
    fat: 1.3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 37,
    slug: 'ayran',
    name: 'Ayran',
    calories: 89,
    protein: 5,
    carbs: 6,
    fat: 5,
    serving_size: '1 Bardak',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 38,
    slug: 'turk_cayi_sekersiz',
    name: 'Türk Çayı (Şekersiz)',
    calories: 2,
    protein: 0,
    carbs: 0.4,
    fat: 0,
    serving_size: '1 Bardak',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 39,
    slug: 'turk_kahvesi_sade',
    name: 'Türk Kahvesi (Sade)',
    calories: 3,
    protein: 0.2,
    carbs: 0.4,
    fat: 0.1,
    serving_size: '1 Fincan',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 40,
    slug: 'tost_kasarli',
    name: 'Tost (Kaşarlı)',
    calories: 435,
    protein: 19.5,
    carbs: 42,
    fat: 21,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 41,
    slug: 'karniyarik',
    name: 'Karnıyarık',
    calories: 245,
    protein: 15.6,
    carbs: 19.6,
    fat: 11.6,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 42,
    slug: 'cacik',
    name: 'Cacık',
    calories: 103,
    protein: 5.6,
    carbs: 7,
    fat: 5.8,
    serving_size: '1 Kase',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 43,
    slug: 'baklava',
    name: 'Baklava',
    calories: 171,
    protein: 2.1,
    carbs: 20.8,
    fat: 8.8,
    serving_size: '1 Adet',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 44,
    slug: 'kunefe',
    name: 'Künefe',
    calories: 712,
    protein: 16,
    carbs: 90,
    fat: 32,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 45,
    slug: 'elma',
    name: 'Elma',
    calories: 104,
    protein: 0.5,
    carbs: 24.8,
    fat: 0.3,
    serving_size: '1 Adet',
    serving_grams: 180,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 46,
    slug: 'muz',
    name: 'Muz',
    calories: 118,
    protein: 1.3,
    carbs: 27.4,
    fat: 0.4,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 47,
    slug: 'cig_kofte_ev_yapimi',
    name: 'Çiğ Köfte (Ev Yapımı)',
    calories: 266,
    protein: 7.5,
    carbs: 42,
    fat: 7.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 48,
    slug: 'gozleme_peynirli',
    name: 'Gözleme (Peynirli)',
    calories: 430,
    protein: 16.2,
    carbs: 50.3,
    fat: 18.2,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 49,
    slug: 'portakal',
    name: 'Portakal',
    calories: 79,
    protein: 1.4,
    carbs: 18,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 50,
    slug: 'mandalina',
    name: 'Mandalina',
    calories: 44,
    protein: 0.6,
    carbs: 10,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 75,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 51,
    slug: 'cilek',
    name: 'Çilek',
    calories: 55,
    protein: 1,
    carbs: 11.6,
    fat: 0.5,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 52,
    slug: 'uzum',
    name: 'Üzüm',
    calories: 115,
    protein: 1,
    carbs: 27,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 53,
    slug: 'karpuz',
    name: 'Karpuz',
    calories: 69,
    protein: 1.2,
    carbs: 15.2,
    fat: 0.4,
    serving_size: '1 Dilim',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 54,
    slug: 'kavun',
    name: 'Kavun',
    calories: 76,
    protein: 1.6,
    carbs: 16.4,
    fat: 0.4,
    serving_size: '1 Dilim',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 55,
    slug: 'armut',
    name: 'Armut',
    calories: 107,
    protein: 0.7,
    carbs: 25.5,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 170,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 56,
    slug: 'kiraz',
    name: 'Kiraz',
    calories: 106,
    protein: 1.7,
    carbs: 24,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 57,
    slug: 'erik',
    name: 'Erik',
    calories: 33,
    protein: 0.5,
    carbs: 7.4,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 65,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 58,
    slug: 'i_ncir_taze',
    name: 'İncir (Taze)',
    calories: 42,
    protein: 0.4,
    carbs: 9.6,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 59,
    slug: 'nar',
    name: 'Nar',
    calories: 92,
    protein: 1.7,
    carbs: 18.7,
    fat: 1.2,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Akdeniz'],
  },

  {
    id: 60,
    slug: 'kivi',
    name: 'Kivi',
    calories: 51,
    protein: 0.8,
    carbs: 11,
    fat: 0.4,
    serving_size: '1 Adet',
    serving_grams: 75,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 61,
    slug: 'ananas',
    name: 'Ananas',
    calories: 55,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    serving_size: '1 Dilim',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 62,
    slug: 'kayisi_taze',
    name: 'Kayısı (Taze)',
    calories: 19,
    protein: 0.5,
    carbs: 3.9,
    fat: 0.1,
    serving_size: '1 Adet',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 63,
    slug: 'hurma_medjool',
    name: 'Hurma (Medjool)',
    calories: 74,
    protein: 0.4,
    carbs: 18,
    fat: 0,
    serving_size: '1 Adet',
    serving_grams: 24,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 64,
    slug: 'greyfurt',
    name: 'Greyfurt',
    calories: 71,
    protein: 1.2,
    carbs: 16,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 65,
    slug: 'domates',
    name: 'Domates',
    calories: 25,
    protein: 1.1,
    carbs: 4.7,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Düşük GI'],
  },

  {
    id: 66,
    slug: 'salatalik',
    name: 'Salatalık',
    calories: 36,
    protein: 1.4,
    carbs: 7.2,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 67,
    slug: 'marul',
    name: 'Marul',
    calories: 17,
    protein: 0.9,
    carbs: 3,
    fat: 0.1,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 68,
    slug: 'havuc',
    name: 'Havuç',
    calories: 26,
    protein: 0.5,
    carbs: 5.8,
    fat: 0.1,
    serving_size: '1 Adet',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 69,
    slug: 'brokoli_haslanmis',
    name: 'Brokoli (Haşlanmış)',
    calories: 63,
    protein: 3.6,
    carbs: 10.8,
    fat: 0.6,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 70,
    slug: 'karnabahar_haslanmis',
    name: 'Karnabahar (Haşlanmış)',
    calories: 42,
    protein: 2.7,
    carbs: 6.1,
    fat: 0.8,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI', 'Keto'],
  },

  {
    id: 71,
    slug: 'kabak_havuc',
    name: 'Kabak (Havuç)',
    calories: 40,
    protein: 2.4,
    carbs: 6.2,
    fat: 0.6,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 72,
    slug: 'patlican_izgara',
    name: 'Patlıcan (Izgara)',
    calories: 72,
    protein: 1.4,
    carbs: 15.7,
    fat: 0.4,
    serving_size: '1 Porsiyon',
    serving_grams: 180,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 73,
    slug: 'biber_dolmalik',
    name: 'Biber (Dolmalık)',
    calories: 24,
    protein: 0.9,
    carbs: 4.6,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 74,
    slug: 'roka',
    name: 'Roka',
    calories: 26,
    protein: 2.1,
    carbs: 3,
    fat: 0.6,
    serving_size: '1 Kase',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 75,
    slug: 'mantar_beyaz',
    name: 'Mantar (Beyaz)',
    calories: 28,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 76,
    slug: 'patates_haslanmis',
    name: 'Patates (Haşlanmış)',
    calories: 134,
    protein: 2.8,
    carbs: 30.2,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 77,
    slug: 'misir_haslanmis',
    name: 'Mısır (Haşlanmış)',
    calories: 111,
    protein: 3.4,
    carbs: 21,
    fat: 1.5,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 78,
    slug: 'bezelye_haslanmis',
    name: 'Bezelye (Haşlanmış)',
    calories: 129,
    protein: 8.1,
    carbs: 23.4,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein'],
  },

  {
    id: 79,
    slug: 'dana_biftek_izgara',
    name: 'Dana Biftek (Izgara)',
    calories: 399,
    protein: 39,
    carbs: 0,
    fat: 27,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 80,
    slug: 'kuzu_pirzola_izgara',
    name: 'Kuzu Pirzola (Izgara)',
    calories: 347,
    protein: 30,
    carbs: 0,
    fat: 25.2,
    serving_size: '1 Porsiyon',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 81,
    slug: 'dana_kiyma_15_yag',
    name: 'Dana Kıyma (%15 Yağ)',
    calories: 359,
    protein: 39,
    carbs: 0,
    fat: 22.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 82,
    slug: 'hindi_gogsu_izgara',
    name: 'Hindi Göğsü (Izgara)',
    calories: 194,
    protein: 45,
    carbs: 0,
    fat: 1.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 83,
    slug: 'tavuk_kanat_firin',
    name: 'Tavuk Kanat (Fırın)',
    calories: 430,
    protein: 40,
    carbs: 0,
    fat: 30,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 84,
    slug: 'ton_baligi_konserve_suda',
    name: 'Ton Balığı (Konserve, Suda)',
    calories: 113,
    protein: 26,
    carbs: 0,
    fat: 1,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Keto', 'Akdeniz'],
  },

  {
    id: 85,
    slug: 'levrek_izgara',
    name: 'Levrek (Izgara)',
    calories: 179,
    protein: 36,
    carbs: 0,
    fat: 3.9,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Keto', 'Akdeniz'],
  },

  {
    id: 86,
    slug: 'cupra_izgara',
    name: 'Çupra (Izgara)',
    calories: 187,
    protein: 31.5,
    carbs: 0,
    fat: 6.8,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Akdeniz'],
  },

  {
    id: 87,
    slug: 'hamsi_kizartma',
    name: 'Hamsi (Kızartma)',
    calories: 205,
    protein: 22,
    carbs: 0,
    fat: 13,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Akdeniz'],
  },

  {
    id: 88,
    slug: 'karides_haslanmis',
    name: 'Karides (Haşlanmış)',
    calories: 119,
    protein: 28.8,
    carbs: 0,
    fat: 0.4,
    serving_size: '1 Porsiyon',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Keto', 'Akdeniz'],
  },

  {
    id: 89,
    slug: 'adana_kebap',
    name: 'Adana Kebap',
    calories: 374,
    protein: 33,
    carbs: 3,
    fat: 25.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 90,
    slug: 'sis_kebap_kuzu',
    name: 'Şiş Kebap (Kuzu)',
    calories: 326,
    protein: 36,
    carbs: 1.5,
    fat: 19.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 91,
    slug: 'pastirma',
    name: 'Pastırma',
    calories: 36,
    protein: 4.4,
    carbs: 0.2,
    fat: 2,
    serving_size: '1 Dilim',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 92,
    slug: 'sucuk',
    name: 'Sucuk',
    calories: 221,
    protein: 11.5,
    carbs: 1,
    fat: 19,
    serving_size: '1 Dilim',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 93,
    slug: 'kasar_peyniri',
    name: 'Kaşar Peyniri',
    calories: 95,
    protein: 6.3,
    carbs: 0.5,
    fat: 7.5,
    serving_size: '1 Dilim',
    serving_grams: 25,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 94,
    slug: 'labne',
    name: 'Labne',
    calories: 184,
    protein: 6,
    carbs: 4,
    fat: 16,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto'],
  },

  {
    id: 95,
    slug: 'kefir',
    name: 'Kefir',
    calories: 127,
    protein: 6.6,
    carbs: 9.4,
    fat: 7,
    serving_size: '1 Bardak',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 96,
    slug: 'suzme_yogurt',
    name: 'Süzme Yoğurt',
    calories: 149,
    protein: 15,
    carbs: 5.4,
    fat: 7.5,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Akdeniz'],
  },

  {
    id: 97,
    slug: 'tereyagi',
    name: 'Tereyağı',
    calories: 73,
    protein: 0.1,
    carbs: 0,
    fat: 8.1,
    serving_size: '1 Dilim',
    serving_grams: 10,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto'],
  },

  {
    id: 98,
    slug: 'krema_35',
    name: 'Krema (%35)',
    calories: 51,
    protein: 0.3,
    carbs: 0.4,
    fat: 5.4,
    serving_size: '1 Porsiyon',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto'],
  },

  {
    id: 99,
    slug: 'beyaz_ekmek',
    name: 'Beyaz Ekmek',
    calories: 79,
    protein: 2.7,
    carbs: 14.7,
    fat: 1,
    serving_size: '1 Dilim',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 100,
    slug: 'bazlama',
    name: 'Bazlama',
    calories: 267,
    protein: 8,
    carbs: 52,
    fat: 3,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 101,
    slug: 'lavas',
    name: 'Lavaş',
    calories: 167,
    protein: 5.4,
    carbs: 32.4,
    fat: 1.8,
    serving_size: '1 Adet',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 102,
    slug: 'nohutlu_pilav',
    name: 'Nohutlu Pilav',
    calories: 332,
    protein: 9,
    carbs: 56,
    fat: 8,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 103,
    slug: 'misir_gevregi',
    name: 'Mısır Gevreği',
    calories: 160,
    protein: 3.6,
    carbs: 33.6,
    fat: 1.2,
    serving_size: '1 Kase',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 104,
    slug: 'granola',
    name: 'Granola',
    calories: 238,
    protein: 5,
    carbs: 32,
    fat: 10,
    serving_size: '1 Kase',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 105,
    slug: 'ceviz',
    name: 'Ceviz',
    calories: 28,
    protein: 0.6,
    carbs: 0.6,
    fat: 2.6,
    serving_size: '1 Adet',
    serving_grams: 4,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 106,
    slug: 'findik',
    name: 'Fındık',
    calories: 11,
    protein: 0.3,
    carbs: 0.3,
    fat: 1,
    serving_size: '1 Adet',
    serving_grams: 2,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 107,
    slug: 'fistik',
    name: 'Fıstık',
    calories: 31,
    protein: 1.3,
    carbs: 0.8,
    fat: 2.5,
    serving_size: '1 Adet',
    serving_grams: 5,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 108,
    slug: 'ay_cekirdegi_cekilmis',
    name: 'Ay Çekirdeği (Çekilmiş)',
    calories: 187,
    protein: 6.3,
    carbs: 6,
    fat: 15.3,
    serving_size: '1 Kase',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 109,
    slug: 'chia_tohumu',
    name: 'Chia Tohumu',
    calories: 61,
    protein: 2,
    carbs: 5,
    fat: 3.7,
    serving_size: '1 Porsiyon',
    serving_grams: 12,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein'],
  },

  {
    id: 110,
    slug: 'zeytinyagli_fasulye',
    name: 'Zeytinyağlı Fasulye',
    calories: 192,
    protein: 5,
    carbs: 16,
    fat: 12,
    serving_size: '1 Tabak',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
  },

  {
    id: 111,
    slug: 'i_mam_bayildi',
    name: 'İmam Bayıldı',
    calories: 209,
    protein: 3.8,
    carbs: 17.5,
    fat: 13.8,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 112,
    slug: 'yaprak_sarma',
    name: 'Yaprak Sarma',
    calories: 44,
    protein: 1,
    carbs: 6.3,
    fat: 1.6,
    serving_size: '1 Adet',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 113,
    slug: 'dolma_biber',
    name: 'Dolma (Biber)',
    calories: 162,
    protein: 3.8,
    carbs: 18,
    fat: 8.3,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 114,
    slug: 'hunkar_begendi',
    name: 'Hünkar Beğendi',
    calories: 363,
    protein: 15,
    carbs: 25,
    fat: 22.5,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 115,
    slug: 'etli_nohut',
    name: 'Etli Nohut',
    calories: 300,
    protein: 18,
    carbs: 30,
    fat: 12,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Yüksek Lif'],
  },

  {
    id: 116,
    slug: 'ezogelin_corbasi',
    name: 'Ezogelin Çorbası',
    calories: 154,
    protein: 7.5,
    carbs: 22.5,
    fat: 3.8,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 117,
    slug: 'tarhana_corbasi',
    name: 'Tarhana Çorbası',
    calories: 132,
    protein: 6.3,
    carbs: 20,
    fat: 3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 118,
    slug: 'i_skembe_corbasi',
    name: 'İşkembe Çorbası',
    calories: 122,
    protein: 11.3,
    carbs: 5,
    fat: 6.3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 119,
    slug: 'pilav_ustu_doner_tavuk',
    name: 'Pilav Üstü Döner (Tavuk)',
    calories: 651,
    protein: 52.5,
    carbs: 63,
    fat: 21,
    serving_size: '1 Porsiyon',
    serving_grams: 350,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 120,
    slug: 'kokorec',
    name: 'Kokoreç',
    calories: 477,
    protein: 27,
    carbs: 4.5,
    fat: 39,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 121,
    slug: 'midye_dolma',
    name: 'Midye Dolma',
    calories: 94,
    protein: 6,
    carbs: 5,
    fat: 5.5,
    serving_size: '1 Adet',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Akdeniz'],
  },

  {
    id: 122,
    slug: 'mercimek_koftesi',
    name: 'Mercimek Köftesi',
    calories: 240,
    protein: 10.5,
    carbs: 36,
    fat: 6,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 123,
    slug: 'pide_kiymali',
    name: 'Pide (Kıymalı)',
    calories: 730,
    protein: 35,
    carbs: 80,
    fat: 30,
    serving_size: '1 Adet',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 124,
    slug: 'humus',
    name: 'Humus',
    calories: 178,
    protein: 8,
    carbs: 14,
    fat: 10,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif', 'Yüksek Protein'],
  },

  {
    id: 125,
    slug: 'revani',
    name: 'Revani',
    calories: 338,
    protein: 5,
    carbs: 48,
    fat: 14,
    serving_size: '1 Dilim',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 126,
    slug: 'sutlac',
    name: 'Sütlaç',
    calories: 217,
    protein: 7,
    carbs: 36,
    fat: 5,
    serving_size: '1 Kase',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 127,
    slug: 'asure',
    name: 'Aşure',
    calories: 295,
    protein: 7.5,
    carbs: 55,
    fat: 5,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 128,
    slug: 'helva_tahin',
    name: 'Helva (Tahin)',
    calories: 276,
    protein: 6,
    carbs: 27,
    fat: 16,
    serving_size: '1 Dilim',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz'],
  },

  {
    id: 129,
    slug: 'lokum',
    name: 'Lokum',
    calories: 39,
    protein: 0,
    carbs: 9.8,
    fat: 0,
    serving_size: '1 Adet',
    serving_grams: 12,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 130,
    slug: 'zeytin_siyah',
    name: 'Zeytin (Siyah)',
    calories: 45,
    protein: 0.3,
    carbs: 2.2,
    fat: 3.9,
    serving_size: '1 Adet',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Keto'],
  },

  {
    id: 131,
    slug: 'zeytin_yesil',
    name: 'Zeytin (Yeşil)',
    calories: 55,
    protein: 0.4,
    carbs: 1.3,
    fat: 5.3,
    serving_size: '1 Adet',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Keto'],
  },

  {
    id: 132,
    slug: 'bal',
    name: 'Bal',
    calories: 69,
    protein: 0.1,
    carbs: 17.2,
    fat: 0,
    serving_size: '1 Porsiyon',
    serving_grams: 21,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 133,
    slug: 'recel_kayisi',
    name: 'Reçel (Kayısı)',
    calories: 56,
    protein: 0.1,
    carbs: 13.8,
    fat: 0,
    serving_size: '1 Porsiyon',
    serving_grams: 20,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 134,
    slug: 'protein_bar',
    name: 'Protein Bar',
    calories: 237,
    protein: 18,
    carbs: 21,
    fat: 9,
    serving_size: '1 Adet',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 135,
    slug: 'sosis_dana',
    name: 'Sosis (Dana)',
    calories: 239,
    protein: 9.6,
    carbs: 1.6,
    fat: 21.6,
    serving_size: '1 Adet',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 136,
    slug: 'tavuk_sis',
    name: 'Tavuk Şiş',
    calories: 242,
    protein: 42,
    carbs: 1.5,
    fat: 7.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 137,
    slug: 'firin_tavuk_but',
    name: 'Fırın Tavuk But',
    calories: 224,
    protein: 26.4,
    carbs: 0,
    fat: 13.2,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 138,
    slug: 'kisir',
    name: 'Kısır',
    calories: 309,
    protein: 9,
    carbs: 48,
    fat: 9,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
  },

  {
    id: 139,
    slug: 'pilav_tereyagli',
    name: 'Pilav (Tereyağlı)',
    calories: 288,
    protein: 5.6,
    carbs: 52,
    fat: 6.4,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 140,
    slug: 'soya_sutu',
    name: 'Soya Sütü',
    calories: 131,
    protein: 7.9,
    carbs: 15.1,
    fat: 4.3,
    serving_size: '1 Bardak',
    serving_grams: 240,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  // ── Expanded catalog (pending verification) ──────────────────────────────

  {
    id: 141,
    slug: 'seftali',
    name: 'Şeftali',
    calories: 59,
    protein: 1.4,
    carbs: 14,
    fat: 0.4,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 142,
    slug: 'ayva',
    name: 'Ayva',
    calories: 57,
    protein: 0.4,
    carbs: 15,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 143,
    slug: 'limon',
    name: 'Limon',
    calories: 17,
    protein: 0.6,
    carbs: 5.4,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 144,
    slug: 'visne',
    name: 'Vişne',
    calories: 50,
    protein: 1,
    carbs: 12,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 145,
    slug: 'bogurtlen',
    name: 'Böğürtlen',
    calories: 43,
    protein: 1.4,
    carbs: 10,
    fat: 0.5,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 146,
    slug: 'ahududu',
    name: 'Ahududu',
    calories: 52,
    protein: 1.2,
    carbs: 12,
    fat: 0.7,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 147,
    slug: 'dut_taze',
    name: 'Dut (Taze)',
    calories: 43,
    protein: 1.4,
    carbs: 10,
    fat: 0.4,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 148,
    slug: 'mango',
    name: 'Mango',
    calories: 99,
    protein: 1.4,
    carbs: 25,
    fat: 0.6,
    serving_size: '1 Adet',
    serving_grams: 165,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 149,
    slug: 'papaya',
    name: 'Papaya',
    calories: 59,
    protein: 0.9,
    carbs: 15,
    fat: 0.4,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 150,
    slug: 'kayisi_kuru',
    name: 'Kayısı (Kuru)',
    calories: 48,
    protein: 0.7,
    carbs: 12.5,
    fat: 0.1,
    serving_size: '1 Adet',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 151,
    slug: 'kuru_uzum',
    name: 'Kuru Üzüm',
    calories: 129,
    protein: 1.3,
    carbs: 34,
    fat: 0.2,
    serving_size: '1 Kase',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 152,
    slug: 'sogan_cig',
    name: 'Soğan (Çiğ)',
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 153,
    slug: 'sarimsak',
    name: 'Sarımsak',
    calories: 13,
    protein: 0.6,
    carbs: 3,
    fat: 0,
    serving_size: '1 Diş',
    serving_grams: 3,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 154,
    slug: 'lahana_beyaz',
    name: 'Lahana (Beyaz)',
    calories: 25,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 155,
    slug: 'kereviz',
    name: 'Kereviz',
    calories: 16,
    protein: 0.7,
    carbs: 3,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 156,
    slug: 'pirasa',
    name: 'Pırasa',
    calories: 54,
    protein: 1.3,
    carbs: 12.6,
    fat: 0.3,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 157,
    slug: 'enginar',
    name: 'Enginar',
    calories: 53,
    protein: 3.3,
    carbs: 11.8,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 158,
    slug: 'bamya_haslanmis',
    name: 'Bamya (Haşlanmış)',
    calories: 33,
    protein: 2,
    carbs: 7.5,
    fat: 0.2,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 159,
    slug: 'semizotu',
    name: 'Semizotu',
    calories: 20,
    protein: 2,
    carbs: 3.4,
    fat: 0.4,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 160,
    slug: 'taze_fasulye',
    name: 'Taze Fasulye',
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.1,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 161,
    slug: 'barbunya_haslanmis',
    name: 'Barbunya (Haşlanmış)',
    calories: 127,
    protein: 8.7,
    carbs: 22.8,
    fat: 0.5,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 162,
    slug: 'patlican_kizartma',
    name: 'Patlıcan Kızartma',
    calories: 320,
    protein: 4,
    carbs: 18,
    fat: 26,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 163,
    slug: 'biber_cig',
    name: 'Biber (Çiğ)',
    calories: 31,
    protein: 1,
    carbs: 7,
    fat: 0.3,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 164,
    slug: 'karnabahar_kizartma',
    name: 'Karnabahar Kızartma',
    calories: 180,
    protein: 5,
    carbs: 14,
    fat: 12,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 165,
    slug: 'patates_kizartmasi',
    name: 'Patates Kızartması',
    calories: 365,
    protein: 4,
    carbs: 48,
    fat: 17,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 166,
    slug: 'kaskaval_peyniri',
    name: 'Kaşkaval Peyniri',
    calories: 113,
    protein: 7,
    carbs: 1,
    fat: 9,
    serving_size: '1 Dilim',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 167,
    slug: 'cokelek',
    name: 'Çökelek',
    calories: 98,
    protein: 11,
    carbs: 3,
    fat: 4.5,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 168,
    slug: 'kaymak',
    name: 'Kaymak',
    calories: 204,
    protein: 2.5,
    carbs: 3,
    fat: 20,
    serving_size: '1 Porsiyon',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 169,
    slug: 'krem_peynir',
    name: 'Krem Peynir',
    calories: 102,
    protein: 2,
    carbs: 1.6,
    fat: 10,
    serving_size: '1 Porsiyon',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 170,
    slug: 'mozzarella',
    name: 'Mozzarella',
    calories: 85,
    protein: 6.3,
    carbs: 1,
    fat: 6.3,
    serving_size: '1 Dilim',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 171,
    slug: 'yarim_yagli_sut',
    name: 'Yarım Yağlı Süt',
    calories: 102,
    protein: 8,
    carbs: 12,
    fat: 2.4,
    serving_size: '1 Bardak',
    serving_grams: 240,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 172,
    slug: 'yogurt_yarim_yagli',
    name: 'Yoğurt (Yarım Yağlı)',
    calories: 77,
    protein: 4.3,
    carbs: 5.6,
    fat: 3.8,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 173,
    slug: 'cig_yumurta',
    name: 'Yumurta (Çiğ)',
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 4.8,
    serving_size: '1 Adet',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
    review: PENDING_REVIEW,
  },
  {
    id: 174,
    slug: 'sahanda_yumurta',
    name: 'Sahanda Yumurta',
    calories: 196,
    protein: 13,
    carbs: 1,
    fat: 15,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
    review: PENDING_REVIEW,
  },
  {
    id: 175,
    slug: 'sucuklu_yumurta',
    name: 'Sucuklu Yumurta',
    calories: 380,
    protein: 20,
    carbs: 2,
    fat: 32,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
    review: PENDING_REVIEW,
  },
  {
    id: 176,
    slug: 'et_sote',
    name: 'Et Sote',
    calories: 285,
    protein: 28,
    carbs: 6,
    fat: 16,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 177,
    slug: 'tas_kebabi',
    name: 'Tas Kebabı',
    calories: 340,
    protein: 26,
    carbs: 12,
    fat: 22,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 178,
    slug: 'musakka',
    name: 'Musakka',
    calories: 320,
    protein: 14,
    carbs: 22,
    fat: 20,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 179,
    slug: 'etli_guvec',
    name: 'Etli Güveç',
    calories: 310,
    protein: 24,
    carbs: 18,
    fat: 16,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 180,
    slug: 'kofte_ev_yapimi',
    name: 'Köfte (Ev Yapımı)',
    calories: 280,
    protein: 22,
    carbs: 8,
    fat: 18,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 181,
    slug: 'ciger_kizartma',
    name: 'Ciğer (Kızartma)',
    calories: 330,
    protein: 26,
    carbs: 10,
    fat: 20,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 182,
    slug: 'salam',
    name: 'Salam',
    calories: 152,
    protein: 6,
    carbs: 1,
    fat: 14,
    serving_size: '1 Dilim',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 183,
    slug: 'jambon',
    name: 'Jambon',
    calories: 46,
    protein: 5.5,
    carbs: 0.5,
    fat: 2.5,
    serving_size: '1 Dilim',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 184,
    slug: 'eriste_haslanmis',
    name: 'Erişte (Haşlanmış)',
    calories: 220,
    protein: 8,
    carbs: 42,
    fat: 2,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 185,
    slug: 'sehirye_haslanmis',
    name: 'Şehriye (Haşlanmış)',
    calories: 157,
    protein: 5.8,
    carbs: 30.9,
    fat: 0.9,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 186,
    slug: 'spagetti_domates_soslu',
    name: 'Spagetti (Domates Soslu)',
    calories: 280,
    protein: 9,
    carbs: 48,
    fat: 6,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 187,
    slug: 'bulgur_koftesi',
    name: 'Bulgur Köftesi',
    calories: 210,
    protein: 6,
    carbs: 36,
    fat: 5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 188,
    slug: 'kirmizi_mercimek_haslanmis',
    name: 'Kırmızı Mercimek (Haşlanmış)',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 189,
    slug: 'yesil_mercimek_haslanmis',
    name: 'Yeşil Mercimek (Haşlanmış)',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 190,
    slug: 'barbunya_pilaki',
    name: 'Barbunya Pilaki',
    calories: 220,
    protein: 8,
    carbs: 32,
    fat: 7,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 191,
    slug: 'nohut_yemegi',
    name: 'Nohut Yemeği',
    calories: 260,
    protein: 12,
    carbs: 36,
    fat: 8,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 192,
    slug: 'bamya_yemegi',
    name: 'Bamya Yemeği',
    calories: 180,
    protein: 4,
    carbs: 20,
    fat: 9,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 193,
    slug: 'mucver',
    name: 'Mücver',
    calories: 240,
    protein: 8,
    carbs: 18,
    fat: 16,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 194,
    slug: 'patates_salatasi',
    name: 'Patates Salatası',
    calories: 180,
    protein: 3,
    carbs: 24,
    fat: 8,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 195,
    slug: 'coban_salata',
    name: 'Çoban Salata',
    calories: 85,
    protein: 2,
    carbs: 10,
    fat: 4,
    serving_size: '1 Kase',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 196,
    slug: 'piyaz',
    name: 'Piyaz',
    calories: 220,
    protein: 10,
    carbs: 28,
    fat: 8,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 197,
    slug: 'falafel',
    name: 'Falafel',
    calories: 57,
    protein: 2.5,
    carbs: 5.5,
    fat: 3,
    serving_size: '1 Adet',
    serving_grams: 20,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 198,
    slug: 'lahana_sarmasi',
    name: 'Lahana Sarması',
    calories: 120,
    protein: 5,
    carbs: 14,
    fat: 5,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 199,
    slug: 'ispanak_yemegi',
    name: 'Ispanak Yemeği',
    calories: 140,
    protein: 5,
    carbs: 10,
    fat: 9,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 200,
    slug: 'firin_makarna',
    name: 'Fırın Makarna',
    calories: 420,
    protein: 16,
    carbs: 52,
    fat: 16,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 201,
    slug: 'balik_tava',
    name: 'Balık Tava',
    calories: 320,
    protein: 24,
    carbs: 18,
    fat: 18,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 202,
    slug: 'midye_tava',
    name: 'Midye Tava',
    calories: 280,
    protein: 14,
    carbs: 22,
    fat: 16,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz'],
    review: PENDING_REVIEW,
  },
  {
    id: 203,
    slug: 'kumpir',
    name: 'Kumpir',
    calories: 450,
    protein: 12,
    carbs: 58,
    fat: 18,
    serving_size: '1 Adet',
    serving_grams: 350,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 204,
    slug: 'durum_tavuk',
    name: 'Dürüm (Tavuk)',
    calories: 480,
    protein: 28,
    carbs: 48,
    fat: 18,
    serving_size: '1 Adet',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 205,
    slug: 'yayla_corbasi',
    name: 'Yayla Çorbası',
    calories: 145,
    protein: 5,
    carbs: 18,
    fat: 6,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 206,
    slug: 'sehirye_corbasi',
    name: 'Şehriye Çorbası',
    calories: 130,
    protein: 4,
    carbs: 20,
    fat: 4,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 207,
    slug: 'dugun_corbasi',
    name: 'Düğün Çorbası',
    calories: 160,
    protein: 8,
    carbs: 14,
    fat: 8,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 208,
    slug: 'brokoli_corbasi',
    name: 'Brokoli Çorbası',
    calories: 110,
    protein: 5,
    carbs: 12,
    fat: 5,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 209,
    slug: 'yuksuk_corbasi',
    name: 'Yüksük Çorbası',
    calories: 155,
    protein: 6,
    carbs: 22,
    fat: 5,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 210,
    slug: 'tahin_pekmez',
    name: 'Tahin Pekmez',
    calories: 196,
    protein: 4,
    carbs: 28,
    fat: 8,
    serving_size: '1 Porsiyon',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 211,
    slug: 'krep',
    name: 'Krep',
    calories: 180,
    protein: 6,
    carbs: 24,
    fat: 7,
    serving_size: '1 Adet',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 212,
    slug: 'waffle',
    name: 'Waffle',
    calories: 291,
    protein: 7,
    carbs: 38,
    fat: 12,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 213,
    slug: 'pogaca_zeytinli',
    name: 'Poğaça (Zeytinli)',
    calories: 280,
    protein: 6,
    carbs: 32,
    fat: 14,
    serving_size: '1 Adet',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 214,
    slug: 'aycicek_yagi',
    name: 'Ayçiçek Yağı',
    calories: 90,
    protein: 0,
    carbs: 0,
    fat: 10,
    serving_size: '1 Yemek Kaşığı',
    serving_grams: 10,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto'],
    review: PENDING_REVIEW,
  },
  {
    id: 215,
    slug: 'antep_fistigi',
    name: 'Antep Fıstığı',
    calories: 12,
    protein: 0.4,
    carbs: 0.5,
    fat: 1,
    serving_size: '1 Adet',
    serving_grams: 2,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 216,
    slug: 'kaju',
    name: 'Kaju',
    calories: 157,
    protein: 5,
    carbs: 9,
    fat: 12,
    serving_size: '1 Kase',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 217,
    slug: 'leblebi',
    name: 'Leblebi',
    calories: 120,
    protein: 6,
    carbs: 18,
    fat: 2,
    serving_size: '1 Kase',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 218,
    slug: 'karisik_kuruyemis',
    name: 'Karışık Kuruyemiş',
    calories: 175,
    protein: 5,
    carbs: 6,
    fat: 15,
    serving_size: '1 Kase',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 219,
    slug: 'biskuvi_petibor',
    name: 'Bisküvi (Petibör)',
    calories: 52,
    protein: 0.8,
    carbs: 7.5,
    fat: 2,
    serving_size: '1 Adet',
    serving_grams: 10,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 220,
    slug: 'cikolata_sutlu',
    name: 'Çikolata (Sütlü)',
    calories: 150,
    protein: 2,
    carbs: 16,
    fat: 9,
    serving_size: '1 Adet',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 221,
    slug: 'gofret',
    name: 'Gofret',
    calories: 140,
    protein: 2,
    carbs: 18,
    fat: 7,
    serving_size: '1 Adet',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 222,
    slug: 'cips_patates',
    name: 'Cips (Patates)',
    calories: 152,
    protein: 2,
    carbs: 15,
    fat: 10,
    serving_size: '1 Porsiyon',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 223,
    slug: 'kraker',
    name: 'Kraker',
    calories: 120,
    protein: 3,
    carbs: 18,
    fat: 4,
    serving_size: '1 Porsiyon',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 224,
    slug: 'popcorn',
    name: 'Popcorn',
    calories: 93,
    protein: 3,
    carbs: 12,
    fat: 4,
    serving_size: '1 Kase',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 225,
    slug: 'granola_bar',
    name: 'Granola Bar',
    calories: 190,
    protein: 4,
    carbs: 28,
    fat: 7,
    serving_size: '1 Adet',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 226,
    slug: 'irmik_helvasi',
    name: 'İrmik Helvası',
    calories: 280,
    protein: 4,
    carbs: 38,
    fat: 13,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 227,
    slug: 'lokma',
    name: 'Lokma',
    calories: 75,
    protein: 1,
    carbs: 10,
    fat: 3.5,
    serving_size: '1 Adet',
    serving_grams: 25,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 228,
    slug: 'tursu_karisik',
    name: 'Turşu (Karışık)',
    calories: 20,
    protein: 0.5,
    carbs: 4,
    fat: 0.1,
    serving_size: '1 Porsiyon',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 229,
    slug: 'peynirli_tost',
    name: 'Peynirli Tost',
    calories: 340,
    protein: 14,
    carbs: 36,
    fat: 16,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 230,
    slug: 'sucuklu_pide',
    name: 'Sucuklu Pide',
    calories: 680,
    protein: 28,
    carbs: 72,
    fat: 32,
    serving_size: '1 Adet',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 231,
    slug: 'tavuklu_salata',
    name: 'Tavuklu Salata',
    calories: 220,
    protein: 24,
    carbs: 10,
    fat: 10,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Akdeniz'],
    review: PENDING_REVIEW,
  },
  {
    id: 232,
    slug: 'ton_salata',
    name: 'Ton Salata',
    calories: 195,
    protein: 22,
    carbs: 8,
    fat: 9,
    serving_size: '1 Kase',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Akdeniz'],
    review: PENDING_REVIEW,
  },
  {
    id: 233,
    slug: 'mercimek_salatasi',
    name: 'Mercimek Salatası',
    calories: 180,
    protein: 10,
    carbs: 26,
    fat: 5,
    serving_size: '1 Kase',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein', 'Akdeniz'],
    review: PENDING_REVIEW,
  },
  {
    id: 234,
    slug: 'zeytinyagli_enginar',
    name: 'Zeytinyağlı Enginar',
    calories: 160,
    protein: 4,
    carbs: 14,
    fat: 10,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 235,
    slug: 'fasulye_pilaki',
    name: 'Fasulye Pilaki',
    calories: 210,
    protein: 7,
    carbs: 30,
    fat: 7,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
    review: PENDING_REVIEW,
  },
  {
    id: 236,
    slug: 'karniyarik_kiyma',
    name: 'Karnıyarık (Kıymalı)',
    calories: 340,
    protein: 16,
    carbs: 18,
    fat: 24,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 237,
    slug: 'tavuk_sote',
    name: 'Tavuk Sote',
    calories: 260,
    protein: 32,
    carbs: 8,
    fat: 11,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
    review: PENDING_REVIEW,
  },
  {
    id: 238,
    slug: 'balik_izgara',
    name: 'Balık (Izgara)',
    calories: 206,
    protein: 34,
    carbs: 0,
    fat: 7,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Keto'],
    review: PENDING_REVIEW,
  },
  {
    id: 239,
    slug: 'muzlu_sut',
    name: 'Muzlu Süt',
    calories: 180,
    protein: 7,
    carbs: 28,
    fat: 4,
    serving_size: '1 Bardak',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  },
  {
    id: 240,
    slug: 'cay_sutlu',
    name: 'Çay (Sütlü)',
    calories: 45,
    protein: 1.5,
    carbs: 6,
    fat: 1.5,
    serving_size: '1 Fincan',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
    review: PENDING_REVIEW,
  }]

/** Legacy export — consumed by foodService, AddMealModal, foodData */
export const FOOD_DB = MASTER_FOOD_DB.map(toLegacyFood)

/** Primary display unit — natural serving label */
export function getPrimaryUnit(food) {
  if (food?._natural?.unit) return food._natural.unit
  if (!food?.units) return 'Gram'
  return Object.keys(food.units).find((u) => u !== 'Gram' && u !== 'Mililitre') ?? Object.keys(food.units)[0]
}

/** Macros for 1× natural serving */
export function getServingPreview(food) {
  if (food?._natural) {
    const n = food._natural
    return {
      unit: n.unit,
      kcal: n.calories,
      protein: n.protein,
      carbs: n.carbs,
      fat: n.fat,
      grams: n.grams,
    }
  }
  const unit = getPrimaryUnit(food)
  const mult = food.units[unit] ?? 0.01
  return {
    unit,
    kcal: Math.round(food.calories * mult),
    protein: Math.round(food.protein * mult * 10) / 10,
    carbs: Math.round(food.carbs * mult * 10) / 10,
    fat: Math.round(food.fat * mult * 10) / 10,
    grams: Math.round(mult * 100),
  }
}
