/**
 * Kalorimetre MASTER Food Database — MVP Nutrition Dataset
 *
 * Source of truth: natural serving macros (NOT per 100 g).
 * calories / protein / carbs / fat = values for serving_size (e.g. "1 Kase").
 * calories always equals Atwater sum: 4×Protein + 4×Carbs + 9×Fat.
 *
 * FOOD_DB is a legacy projection for UI calcPreview / unit scaling.
 */

/** Atwater general factors */
export function macroCalories(protein, carbs, fat) {
  return Math.round(protein * 4 + carbs * 4 + fat * 9)
}

/** Parse "1 Kase" → { qty: 1, unit: "Kase" } */
export function parseServingSize(servingSize) {
  const m = String(servingSize || '').match(/^(\d+(?:\.\d+)?)\s+(.+)$/)
  if (m) return { qty: parseFloat(m[1]), unit: m[2] }
  return { qty: 1, unit: servingSize || 'Porsiyon' }
}

/** Build legacy FOOD_DB row from a master entry (UI basket scaling). */
export function toLegacyFood(master) {
  const { unit } = parseServingSize(master.serving_size)
  const mult = Math.max(master.serving_grams / 100, 0.01)

  const legacy = {
    id: master.id,
    slug: master.slug,
    name: master.name,
    calories: master.calories / mult,
    protein: master.protein / mult,
    carbs: master.carbs / mult,
    fat: master.fat / mult,
    units: { Gram: 0.01, [unit]: mult },
    tags: master.tags ?? [],
    serving_size: master.serving_size,
    data_source: master.data_source,
    _natural: {
      calories: master.calories,
      protein: master.protein,
      carbs: master.carbs,
      fat: master.fat,
      unit,
      grams: master.serving_grams,
    },
  }

  if (unit === 'Bardak' || unit === 'Fincan' || unit === 'Su Bardağı') {
    legacy.units.Mililitre = 0.01
  }

  return legacy
}

export const MASTER_FOOD_DB = [
  {
    id: 1,
    slug: 'izgara_kofte',
    name: 'Izgara Köfte',
    calories: 309,
    protein: 27,
    carbs: 3,
    fat: 21,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 2,
    slug: 'tavuk_gogsu_izgara',
    name: 'Tavuk Göğsü (Izgara)',
    calories: 229,
    protein: 46,
    carbs: 0,
    fat: 5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 3,
    slug: 'yulaf_ezmesi',
    name: 'Yulaf Ezmesi',
    calories: 191,
    protein: 8,
    carbs: 33,
    fat: 3,
    serving_size: '1 Kase',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 4,
    slug: 'mercimek_corbasi',
    name: 'Mercimek Çorbası',
    calories: 155,
    protein: 10,
    carbs: 22,
    fat: 3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI', 'Akdeniz'],
  },

  {
    id: 5,
    slug: 'tam_bugday_ekmek',
    name: 'Tam Buğday Ekmek',
    calories: 85,
    protein: 5,
    carbs: 14,
    fat: 1,
    serving_size: '1 Dilim',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 6,
    slug: 'haslanmis_yumurta',
    name: 'Haşlanmış Yumurta',
    calories: 71,
    protein: 6,
    carbs: 0.6,
    fat: 5,
    serving_size: '1 Adet',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 7,
    slug: 'pirinc_pilavi',
    name: 'Pirinç Pilavı',
    calories: 189,
    protein: 4,
    carbs: 42,
    fat: 0.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 8,
    slug: 'kuru_fasulye',
    name: 'Kuru Fasulye',
    calories: 283,
    protein: 18,
    carbs: 46,
    fat: 3,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 9,
    slug: 'zeytinyagli_salata',
    name: 'Zeytinyağlı Salata',
    calories: 128,
    protein: 2.3,
    carbs: 6,
    fat: 10.5,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Akdeniz', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 10,
    slug: 'tam_yagli_sut',
    name: 'Tam Yağlı Süt',
    calories: 123,
    protein: 6.4,
    carbs: 9.6,
    fat: 6.6,
    serving_size: '1 Su Bardağı',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 11,
    slug: 'somon_izgara',
    name: 'Somon (Izgara)',
    calories: 300,
    protein: 30,
    carbs: 0,
    fat: 20,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Akdeniz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 12,
    slug: 'kinoa',
    name: 'Kinoa',
    calories: 178,
    protein: 6.6,
    carbs: 31.5,
    fat: 2.8,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Düşük GI'],
  },

  {
    id: 13,
    slug: 'avokado',
    name: 'Avokado',
    calories: 269,
    protein: 3,
    carbs: 13.5,
    fat: 22.5,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Keto', 'Akdeniz', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 14,
    slug: 'yogurt_tam_yagli',
    name: 'Yoğurt (Tam Yağlı)',
    calories: 94,
    protein: 5.3,
    carbs: 7.1,
    fat: 4.9,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 15,
    slug: 'nohut_haslanmis',
    name: 'Nohut (Haşlanmış)',
    calories: 251,
    protein: 13.4,
    carbs: 40.5,
    fat: 3.9,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI', 'Akdeniz'],
  },

  {
    id: 16,
    slug: 'badem',
    name: 'Badem',
    calories: 8,
    protein: 0.3,
    carbs: 0.3,
    fat: 0.6,
    serving_size: '1 Adet',
    serving_grams: 1.2,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Keto', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 17,
    slug: 'ispanak_cig',
    name: 'Ispanak (Çiğ)',
    calories: 12,
    protein: 1.2,
    carbs: 1.4,
    fat: 0.2,
    serving_size: '1 Kase',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Akdeniz', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 18,
    slug: 'tatli_patates',
    name: 'Tatlı Patates',
    calories: 105,
    protein: 1.9,
    carbs: 24,
    fat: 0.1,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 19,
    slug: 'lor_peyniri',
    name: 'Lor Peyniri',
    calories: 14,
    protein: 1.7,
    carbs: 0.5,
    fat: 0.6,
    serving_size: '1 Yemek Kaşığı',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 20,
    slug: 'zeytinyagi',
    name: 'Zeytinyağı',
    calories: 135,
    protein: 0,
    carbs: 0,
    fat: 15,
    serving_size: '1 Yemek Kaşığı',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Keto', 'Akdeniz', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 21,
    slug: 'simit',
    name: 'Simit',
    calories: 283,
    protein: 9,
    carbs: 55,
    fat: 3,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 22,
    slug: 'beyaz_peynir',
    name: 'Beyaz Peynir',
    calories: 80,
    protein: 4.3,
    carbs: 1.2,
    fat: 6.4,
    serving_size: '1 Dilim',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 23,
    slug: 'menemen',
    name: 'Menemen',
    calories: 297,
    protein: 14,
    carbs: 13,
    fat: 21,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 24,
    slug: 'omlet',
    name: 'Omlet',
    calories: 120,
    protein: 8.5,
    carbs: 0.5,
    fat: 9.3,
    serving_size: '1 Adet',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 25,
    slug: 'pogaca_peynirli',
    name: 'Poğaça (Peynirli)',
    calories: 290,
    protein: 7.6,
    carbs: 36,
    fat: 12.8,
    serving_size: '1 Adet',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 26,
    slug: 'doner_tavuk',
    name: 'Döner (Tavuk)',
    calories: 225,
    protein: 33,
    carbs: 4.5,
    fat: 8.3,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 27,
    slug: 'doner_et',
    name: 'Döner (Et)',
    calories: 342,
    protein: 29.4,
    carbs: 4.2,
    fat: 23.1,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 28,
    slug: 'lahmacun',
    name: 'Lahmacun',
    calories: 256,
    protein: 13,
    carbs: 33,
    fat: 8,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 29,
    slug: 'pide_kasarli',
    name: 'Pide (Kaşarlı)',
    calories: 700,
    protein: 31.3,
    carbs: 87.5,
    fat: 25,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 30,
    slug: 'borek_peynirli_firin',
    name: 'Börek (Peynirli, Fırın)',
    calories: 265,
    protein: 9.4,
    carbs: 25.9,
    fat: 13.8,
    serving_size: '1 Dilim',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 31,
    slug: 'manti',
    name: 'Mantı',
    calories: 555,
    protein: 28.5,
    carbs: 73.8,
    fat: 16.2,
    serving_size: '1 Porsiyon',
    serving_grams: 300,
    data_source: 'MASTER_DB',
    tags: ['Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 32,
    slug: 'i_skender_kebap',
    name: 'İskender Kebap',
    calories: 723,
    protein: 49,
    carbs: 53,
    fat: 35,
    serving_size: '1 Porsiyon',
    serving_grams: 350,
    data_source: 'MASTER_DB',
    tags: ['Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 33,
    slug: 'bulgur_pilavi',
    name: 'Bulgur Pilavı',
    calories: 308,
    protein: 11.2,
    carbs: 60,
    fat: 2.6,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 34,
    slug: 'makarna_haslanmis',
    name: 'Makarna (Haşlanmış)',
    calories: 261,
    protein: 10,
    carbs: 50.4,
    fat: 2.2,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 35,
    slug: 'domates_corbasi',
    name: 'Domates Çorbası',
    calories: 123,
    protein: 4,
    carbs: 20,
    fat: 3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 36,
    slug: 'tavuk_corbasi',
    name: 'Tavuk Çorbası',
    calories: 38,
    protein: 4.5,
    carbs: 2,
    fat: 1.3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 37,
    slug: 'ayran',
    name: 'Ayran',
    calories: 89,
    protein: 5,
    carbs: 6,
    fat: 5,
    serving_size: '1 Bardak',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 38,
    slug: 'turk_cayi_sekersiz',
    name: 'Türk Çayı (Şekersiz)',
    calories: 2,
    protein: 0,
    carbs: 0.4,
    fat: 0,
    serving_size: '1 Bardak',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 39,
    slug: 'turk_kahvesi_sade',
    name: 'Türk Kahvesi (Sade)',
    calories: 3,
    protein: 0.2,
    carbs: 0.4,
    fat: 0.1,
    serving_size: '1 Fincan',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 40,
    slug: 'tost_kasarli',
    name: 'Tost (Kaşarlı)',
    calories: 435,
    protein: 19.5,
    carbs: 42,
    fat: 21,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 41,
    slug: 'karniyarik',
    name: 'Karnıyarık',
    calories: 245,
    protein: 15.6,
    carbs: 19.6,
    fat: 11.6,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 42,
    slug: 'cacik',
    name: 'Cacık',
    calories: 103,
    protein: 5.6,
    carbs: 7,
    fat: 5.8,
    serving_size: '1 Kase',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 43,
    slug: 'baklava',
    name: 'Baklava',
    calories: 171,
    protein: 2.1,
    carbs: 20.8,
    fat: 8.8,
    serving_size: '1 Adet',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 44,
    slug: 'kunefe',
    name: 'Künefe',
    calories: 712,
    protein: 16,
    carbs: 90,
    fat: 32,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 45,
    slug: 'elma',
    name: 'Elma',
    calories: 104,
    protein: 0.5,
    carbs: 24.8,
    fat: 0.3,
    serving_size: '1 Adet',
    serving_grams: 180,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 46,
    slug: 'muz',
    name: 'Muz',
    calories: 118,
    protein: 1.3,
    carbs: 27.4,
    fat: 0.4,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 47,
    slug: 'cig_kofte_ev_yapimi',
    name: 'Çiğ Köfte (Ev Yapımı)',
    calories: 266,
    protein: 7.5,
    carbs: 42,
    fat: 7.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 48,
    slug: 'gozleme_peynirli',
    name: 'Gözleme (Peynirli)',
    calories: 430,
    protein: 16.2,
    carbs: 50.3,
    fat: 18.2,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 49,
    slug: 'portakal',
    name: 'Portakal',
    calories: 79,
    protein: 1.4,
    carbs: 18,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 50,
    slug: 'mandalina',
    name: 'Mandalina',
    calories: 44,
    protein: 0.6,
    carbs: 10,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 75,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 51,
    slug: 'cilek',
    name: 'Çilek',
    calories: 55,
    protein: 1,
    carbs: 11.6,
    fat: 0.5,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 52,
    slug: 'uzum',
    name: 'Üzüm',
    calories: 115,
    protein: 1,
    carbs: 27,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 53,
    slug: 'karpuz',
    name: 'Karpuz',
    calories: 69,
    protein: 1.2,
    carbs: 15.2,
    fat: 0.4,
    serving_size: '1 Dilim',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 54,
    slug: 'kavun',
    name: 'Kavun',
    calories: 76,
    protein: 1.6,
    carbs: 16.4,
    fat: 0.4,
    serving_size: '1 Dilim',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 55,
    slug: 'armut',
    name: 'Armut',
    calories: 107,
    protein: 0.7,
    carbs: 25.5,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 170,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 56,
    slug: 'kiraz',
    name: 'Kiraz',
    calories: 106,
    protein: 1.7,
    carbs: 24,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 57,
    slug: 'erik',
    name: 'Erik',
    calories: 33,
    protein: 0.5,
    carbs: 7.4,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 65,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 58,
    slug: 'i_ncir_taze',
    name: 'İncir (Taze)',
    calories: 42,
    protein: 0.4,
    carbs: 9.6,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 59,
    slug: 'nar',
    name: 'Nar',
    calories: 92,
    protein: 1.7,
    carbs: 18.7,
    fat: 1.2,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Akdeniz'],
  },

  {
    id: 60,
    slug: 'kivi',
    name: 'Kivi',
    calories: 51,
    protein: 0.8,
    carbs: 11,
    fat: 0.4,
    serving_size: '1 Adet',
    serving_grams: 75,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 61,
    slug: 'ananas',
    name: 'Ananas',
    calories: 55,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    serving_size: '1 Dilim',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 62,
    slug: 'kayisi_taze',
    name: 'Kayısı (Taze)',
    calories: 19,
    protein: 0.5,
    carbs: 3.9,
    fat: 0.1,
    serving_size: '1 Adet',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 63,
    slug: 'hurma_medjool',
    name: 'Hurma (Medjool)',
    calories: 74,
    protein: 0.4,
    carbs: 18,
    fat: 0,
    serving_size: '1 Adet',
    serving_grams: 24,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 64,
    slug: 'greyfurt',
    name: 'Greyfurt',
    calories: 71,
    protein: 1.2,
    carbs: 16,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 65,
    slug: 'domates',
    name: 'Domates',
    calories: 25,
    protein: 1.1,
    carbs: 4.7,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Düşük GI'],
  },

  {
    id: 66,
    slug: 'salatalik',
    name: 'Salatalık',
    calories: 36,
    protein: 1.4,
    carbs: 7.2,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 67,
    slug: 'marul',
    name: 'Marul',
    calories: 17,
    protein: 0.9,
    carbs: 3,
    fat: 0.1,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 68,
    slug: 'havuc',
    name: 'Havuç',
    calories: 26,
    protein: 0.5,
    carbs: 5.8,
    fat: 0.1,
    serving_size: '1 Adet',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 69,
    slug: 'brokoli_haslanmis',
    name: 'Brokoli (Haşlanmış)',
    calories: 63,
    protein: 3.6,
    carbs: 10.8,
    fat: 0.6,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Düşük GI'],
  },

  {
    id: 70,
    slug: 'karnabahar_haslanmis',
    name: 'Karnabahar (Haşlanmış)',
    calories: 42,
    protein: 2.7,
    carbs: 6.1,
    fat: 0.8,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI', 'Keto'],
  },

  {
    id: 71,
    slug: 'kabak_havuc',
    name: 'Kabak (Havuç)',
    calories: 40,
    protein: 2.4,
    carbs: 6.2,
    fat: 0.6,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 72,
    slug: 'patlican_izgara',
    name: 'Patlıcan (Izgara)',
    calories: 72,
    protein: 1.4,
    carbs: 15.7,
    fat: 0.4,
    serving_size: '1 Porsiyon',
    serving_grams: 180,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 73,
    slug: 'biber_dolmalik',
    name: 'Biber (Dolmalık)',
    calories: 24,
    protein: 0.9,
    carbs: 4.6,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 74,
    slug: 'roka',
    name: 'Roka',
    calories: 26,
    protein: 2.1,
    carbs: 3,
    fat: 0.6,
    serving_size: '1 Kase',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 75,
    slug: 'mantar_beyaz',
    name: 'Mantar (Beyaz)',
    calories: 28,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Düşük GI'],
  },

  {
    id: 76,
    slug: 'patates_haslanmis',
    name: 'Patates (Haşlanmış)',
    calories: 134,
    protein: 2.8,
    carbs: 30.2,
    fat: 0.2,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 77,
    slug: 'misir_haslanmis',
    name: 'Mısır (Haşlanmış)',
    calories: 111,
    protein: 3.4,
    carbs: 21,
    fat: 1.5,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 78,
    slug: 'bezelye_haslanmis',
    name: 'Bezelye (Haşlanmış)',
    calories: 129,
    protein: 8.1,
    carbs: 23.4,
    fat: 0.3,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein'],
  },

  {
    id: 79,
    slug: 'dana_biftek_izgara',
    name: 'Dana Biftek (Izgara)',
    calories: 399,
    protein: 39,
    carbs: 0,
    fat: 27,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 80,
    slug: 'kuzu_pirzola_izgara',
    name: 'Kuzu Pirzola (Izgara)',
    calories: 347,
    protein: 30,
    carbs: 0,
    fat: 25.2,
    serving_size: '1 Porsiyon',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 81,
    slug: 'dana_kiyma_15_yag',
    name: 'Dana Kıyma (%15 Yağ)',
    calories: 359,
    protein: 39,
    carbs: 0,
    fat: 22.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 82,
    slug: 'hindi_gogsu_izgara',
    name: 'Hindi Göğsü (Izgara)',
    calories: 194,
    protein: 45,
    carbs: 0,
    fat: 1.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 83,
    slug: 'tavuk_kanat_firin',
    name: 'Tavuk Kanat (Fırın)',
    calories: 430,
    protein: 40,
    carbs: 0,
    fat: 30,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 84,
    slug: 'ton_baligi_konserve_suda',
    name: 'Ton Balığı (Konserve, Suda)',
    calories: 113,
    protein: 26,
    carbs: 0,
    fat: 1,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Keto', 'Akdeniz'],
  },

  {
    id: 85,
    slug: 'levrek_izgara',
    name: 'Levrek (Izgara)',
    calories: 179,
    protein: 36,
    carbs: 0,
    fat: 3.9,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Keto', 'Akdeniz'],
  },

  {
    id: 86,
    slug: 'cupra_izgara',
    name: 'Çupra (Izgara)',
    calories: 187,
    protein: 31.5,
    carbs: 0,
    fat: 6.8,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Akdeniz'],
  },

  {
    id: 87,
    slug: 'hamsi_kizartma',
    name: 'Hamsi (Kızartma)',
    calories: 205,
    protein: 22,
    carbs: 0,
    fat: 13,
    serving_size: '1 Porsiyon',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Akdeniz'],
  },

  {
    id: 88,
    slug: 'karides_haslanmis',
    name: 'Karides (Haşlanmış)',
    calories: 119,
    protein: 28.8,
    carbs: 0,
    fat: 0.4,
    serving_size: '1 Porsiyon',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Yüksek Protein', 'Keto', 'Akdeniz'],
  },

  {
    id: 89,
    slug: 'adana_kebap',
    name: 'Adana Kebap',
    calories: 374,
    protein: 33,
    carbs: 3,
    fat: 25.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 90,
    slug: 'sis_kebap_kuzu',
    name: 'Şiş Kebap (Kuzu)',
    calories: 326,
    protein: 36,
    carbs: 1.5,
    fat: 19.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 91,
    slug: 'pastirma',
    name: 'Pastırma',
    calories: 36,
    protein: 4.4,
    carbs: 0.2,
    fat: 2,
    serving_size: '1 Dilim',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 92,
    slug: 'sucuk',
    name: 'Sucuk',
    calories: 221,
    protein: 11.5,
    carbs: 1,
    fat: 19,
    serving_size: '1 Dilim',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 93,
    slug: 'kasar_peyniri',
    name: 'Kaşar Peyniri',
    calories: 95,
    protein: 6.3,
    carbs: 0.5,
    fat: 7.5,
    serving_size: '1 Dilim',
    serving_grams: 25,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 94,
    slug: 'labne',
    name: 'Labne',
    calories: 184,
    protein: 6,
    carbs: 4,
    fat: 16,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto'],
  },

  {
    id: 95,
    slug: 'kefir',
    name: 'Kefir',
    calories: 127,
    protein: 6.6,
    carbs: 9.4,
    fat: 7,
    serving_size: '1 Bardak',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 96,
    slug: 'suzme_yogurt',
    name: 'Süzme Yoğurt',
    calories: 149,
    protein: 15,
    carbs: 5.4,
    fat: 7.5,
    serving_size: '1 Kase',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Akdeniz'],
  },

  {
    id: 97,
    slug: 'tereyagi',
    name: 'Tereyağı',
    calories: 73,
    protein: 0.1,
    carbs: 0,
    fat: 8.1,
    serving_size: '1 Dilim',
    serving_grams: 10,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto'],
  },

  {
    id: 98,
    slug: 'krema_35',
    name: 'Krema (%35)',
    calories: 51,
    protein: 0.3,
    carbs: 0.4,
    fat: 5.4,
    serving_size: '1 Porsiyon',
    serving_grams: 15,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Keto'],
  },

  {
    id: 99,
    slug: 'beyaz_ekmek',
    name: 'Beyaz Ekmek',
    calories: 79,
    protein: 2.7,
    carbs: 14.7,
    fat: 1,
    serving_size: '1 Dilim',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 100,
    slug: 'bazlama',
    name: 'Bazlama',
    calories: 267,
    protein: 8,
    carbs: 52,
    fat: 3,
    serving_size: '1 Adet',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 101,
    slug: 'lavas',
    name: 'Lavaş',
    calories: 167,
    protein: 5.4,
    carbs: 32.4,
    fat: 1.8,
    serving_size: '1 Adet',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 102,
    slug: 'nohutlu_pilav',
    name: 'Nohutlu Pilav',
    calories: 332,
    protein: 9,
    carbs: 56,
    fat: 8,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 103,
    slug: 'misir_gevregi',
    name: 'Mısır Gevreği',
    calories: 160,
    protein: 3.6,
    carbs: 33.6,
    fat: 1.2,
    serving_size: '1 Kase',
    serving_grams: 40,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 104,
    slug: 'granola',
    name: 'Granola',
    calories: 238,
    protein: 5,
    carbs: 32,
    fat: 10,
    serving_size: '1 Kase',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 105,
    slug: 'ceviz',
    name: 'Ceviz',
    calories: 28,
    protein: 0.6,
    carbs: 0.6,
    fat: 2.6,
    serving_size: '1 Adet',
    serving_grams: 4,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 106,
    slug: 'findik',
    name: 'Fındık',
    calories: 11,
    protein: 0.3,
    carbs: 0.3,
    fat: 1,
    serving_size: '1 Adet',
    serving_grams: 2,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 107,
    slug: 'fistik',
    name: 'Fıstık',
    calories: 31,
    protein: 1.3,
    carbs: 0.8,
    fat: 2.5,
    serving_size: '1 Adet',
    serving_grams: 5,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 108,
    slug: 'ay_cekirdegi_cekilmis',
    name: 'Ay Çekirdeği (Çekilmiş)',
    calories: 187,
    protein: 6.3,
    carbs: 6,
    fat: 15.3,
    serving_size: '1 Kase',
    serving_grams: 30,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Keto', 'Yüksek Protein'],
  },

  {
    id: 109,
    slug: 'chia_tohumu',
    name: 'Chia Tohumu',
    calories: 61,
    protein: 2,
    carbs: 5,
    fat: 3.7,
    serving_size: '1 Porsiyon',
    serving_grams: 12,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif', 'Yüksek Protein'],
  },

  {
    id: 110,
    slug: 'zeytinyagli_fasulye',
    name: 'Zeytinyağlı Fasulye',
    calories: 192,
    protein: 5,
    carbs: 16,
    fat: 12,
    serving_size: '1 Tabak',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
  },

  {
    id: 111,
    slug: 'i_mam_bayildi',
    name: 'İmam Bayıldı',
    calories: 209,
    protein: 3.8,
    carbs: 17.5,
    fat: 13.8,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 112,
    slug: 'yaprak_sarma',
    name: 'Yaprak Sarma',
    calories: 44,
    protein: 1,
    carbs: 6.3,
    fat: 1.6,
    serving_size: '1 Adet',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 113,
    slug: 'dolma_biber',
    name: 'Dolma (Biber)',
    calories: 162,
    protein: 3.8,
    carbs: 18,
    fat: 8.3,
    serving_size: '1 Adet',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 114,
    slug: 'hunkar_begendi',
    name: 'Hünkar Beğendi',
    calories: 363,
    protein: 15,
    carbs: 25,
    fat: 22.5,
    serving_size: '1 Porsiyon',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 115,
    slug: 'etli_nohut',
    name: 'Etli Nohut',
    calories: 300,
    protein: 18,
    carbs: 30,
    fat: 12,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Yüksek Lif'],
  },

  {
    id: 116,
    slug: 'ezogelin_corbasi',
    name: 'Ezogelin Çorbası',
    calories: 154,
    protein: 7.5,
    carbs: 22.5,
    fat: 3.8,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 117,
    slug: 'tarhana_corbasi',
    name: 'Tarhana Çorbası',
    calories: 132,
    protein: 6.3,
    carbs: 20,
    fat: 3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz'],
  },

  {
    id: 118,
    slug: 'i_skembe_corbasi',
    name: 'İşkembe Çorbası',
    calories: 122,
    protein: 11.3,
    carbs: 5,
    fat: 6.3,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 119,
    slug: 'pilav_ustu_doner_tavuk',
    name: 'Pilav Üstü Döner (Tavuk)',
    calories: 651,
    protein: 52.5,
    carbs: 63,
    fat: 21,
    serving_size: '1 Porsiyon',
    serving_grams: 350,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 120,
    slug: 'kokorec',
    name: 'Kokoreç',
    calories: 477,
    protein: 27,
    carbs: 4.5,
    fat: 39,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 121,
    slug: 'midye_dolma',
    name: 'Midye Dolma',
    calories: 94,
    protein: 6,
    carbs: 5,
    fat: 5.5,
    serving_size: '1 Adet',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Akdeniz'],
  },

  {
    id: 122,
    slug: 'mercimek_koftesi',
    name: 'Mercimek Köftesi',
    calories: 240,
    protein: 10.5,
    carbs: 36,
    fat: 6,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 123,
    slug: 'pide_kiymali',
    name: 'Pide (Kıymalı)',
    calories: 730,
    protein: 35,
    carbs: 80,
    fat: 30,
    serving_size: '1 Adet',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 124,
    slug: 'humus',
    name: 'Humus',
    calories: 178,
    protein: 8,
    carbs: 14,
    fat: 10,
    serving_size: '1 Kase',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif', 'Yüksek Protein'],
  },

  {
    id: 125,
    slug: 'revani',
    name: 'Revani',
    calories: 338,
    protein: 5,
    carbs: 48,
    fat: 14,
    serving_size: '1 Dilim',
    serving_grams: 100,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 126,
    slug: 'sutlac',
    name: 'Sütlaç',
    calories: 217,
    protein: 7,
    carbs: 36,
    fat: 5,
    serving_size: '1 Kase',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 127,
    slug: 'asure',
    name: 'Aşure',
    calories: 295,
    protein: 7.5,
    carbs: 55,
    fat: 5,
    serving_size: '1 Kase',
    serving_grams: 250,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Lif'],
  },

  {
    id: 128,
    slug: 'helva_tahin',
    name: 'Helva (Tahin)',
    calories: 276,
    protein: 6,
    carbs: 27,
    fat: 16,
    serving_size: '1 Dilim',
    serving_grams: 50,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Deniz Ürünsüz'],
  },

  {
    id: 129,
    slug: 'lokum',
    name: 'Lokum',
    calories: 39,
    protein: 0,
    carbs: 9.8,
    fat: 0,
    serving_size: '1 Adet',
    serving_grams: 12,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 130,
    slug: 'zeytin_siyah',
    name: 'Zeytin (Siyah)',
    calories: 45,
    protein: 0.3,
    carbs: 2.2,
    fat: 3.9,
    serving_size: '1 Adet',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Keto'],
  },

  {
    id: 131,
    slug: 'zeytin_yesil',
    name: 'Zeytin (Yeşil)',
    calories: 55,
    protein: 0.4,
    carbs: 1.3,
    fat: 5.3,
    serving_size: '1 Adet',
    serving_grams: 35,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Keto'],
  },

  {
    id: 132,
    slug: 'bal',
    name: 'Bal',
    calories: 69,
    protein: 0.1,
    carbs: 17.2,
    fat: 0,
    serving_size: '1 Porsiyon',
    serving_grams: 21,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 133,
    slug: 'recel_kayisi',
    name: 'Reçel (Kayısı)',
    calories: 56,
    protein: 0.1,
    carbs: 13.8,
    fat: 0,
    serving_size: '1 Porsiyon',
    serving_grams: 20,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 134,
    slug: 'protein_bar',
    name: 'Protein Bar',
    calories: 237,
    protein: 18,
    carbs: 21,
    fat: 9,
    serving_size: '1 Adet',
    serving_grams: 60,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 135,
    slug: 'sosis_dana',
    name: 'Sosis (Dana)',
    calories: 239,
    protein: 9.6,
    carbs: 1.6,
    fat: 21.6,
    serving_size: '1 Adet',
    serving_grams: 80,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 136,
    slug: 'tavuk_sis',
    name: 'Tavuk Şiş',
    calories: 242,
    protein: 42,
    carbs: 1.5,
    fat: 7.5,
    serving_size: '1 Porsiyon',
    serving_grams: 150,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein', 'Keto'],
  },

  {
    id: 137,
    slug: 'firin_tavuk_but',
    name: 'Fırın Tavuk But',
    calories: 224,
    protein: 26.4,
    carbs: 0,
    fat: 13.2,
    serving_size: '1 Adet',
    serving_grams: 120,
    data_source: 'MASTER_DB',
    tags: ['Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Yüksek Protein'],
  },

  {
    id: 138,
    slug: 'kisir',
    name: 'Kısır',
    calories: 309,
    protein: 9,
    carbs: 48,
    fat: 9,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz', 'Akdeniz', 'Yüksek Lif'],
  },

  {
    id: 139,
    slug: 'pilav_tereyagli',
    name: 'Pilav (Tereyağlı)',
    calories: 288,
    protein: 5.6,
    carbs: 52,
    fat: 6.4,
    serving_size: '1 Porsiyon',
    serving_grams: 200,
    data_source: 'MASTER_DB',
    tags: ['Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  },

  {
    id: 140,
    slug: 'soya_sutu',
    name: 'Soya Sütü',
    calories: 131,
    protein: 7.9,
    carbs: 15.1,
    fat: 4.3,
    serving_size: '1 Bardak',
    serving_grams: 240,
    data_source: 'MASTER_DB',
    tags: ['Vegan', 'Vejetaryen', 'Glutensiz', 'Laktozsuz', 'Kuruyemişsiz', 'Deniz Ürünsüz'],
  }]

/** Legacy export — consumed by foodService, AddMealModal, foodData */
export const FOOD_DB = MASTER_FOOD_DB.map(toLegacyFood)

/** Primary display unit — natural serving label */
export function getPrimaryUnit(food) {
  if (food?._natural?.unit) return food._natural.unit
  if (!food?.units) return 'Gram'
  return Object.keys(food.units).find((u) => u !== 'Gram' && u !== 'Mililitre') ?? Object.keys(food.units)[0]
}

/** Macros for 1× natural serving */
export function getServingPreview(food) {
  if (food?._natural) {
    const n = food._natural
    return {
      unit: n.unit,
      kcal: n.calories,
      protein: n.protein,
      carbs: n.carbs,
      fat: n.fat,
      grams: n.grams,
    }
  }
  const unit = getPrimaryUnit(food)
  const mult = food.units[unit] ?? 0.01
  return {
    unit,
    kcal: Math.round(food.calories * mult),
    protein: Math.round(food.protein * mult * 10) / 10,
    carbs: Math.round(food.carbs * mult * 10) / 10,
    fat: Math.round(food.fat * mult * 10) / 10,
    grams: Math.round(mult * 100),
  }
}
